"""Module with dictionary of UBX message types."""

#                      Copyright (c) 2022
#                   Frederick H. G. Wright II
#                          fw@fwright.net
#
#        The information in this software is subject to change
#   without notice and should not be construed as a commitment
#   by Frederick H. G. Wright II, hereafter known as "author".
#   The author makes no representations about the suitability
#   of this software for any purpose.  It is supplied "As Is"
#   without expressed or implied  warranty.
#
#        This software may be copied or distributed for any
#   noncommercial purpose, with the inclusion of this notice,
#   and provided that any modifications are clearly identified
#   as such and are accompanied by the original unmodified
#   software.

# This provides a generic number->name decoding for UBX messages.

UBX_DICT = {
    1: 'NAV',
    2: 'RXM',
    4: 'INF',
    5: 'ACK',
    6: 'CFG',
    9: 'UPD',
    10: 'MON',
    11: 'AID',
    13: 'TIM',
    16: 'ESF',
    19: 'MGA',
    33: 'LOG',
    39: 'SEC',
    40: 'HNR',
    (1, 1): 'NAV-POSECEF',
    (1, 2): 'NAV-POSLLH',
    (1, 3): 'NAV-STATUS',
    (1, 4): 'NAV-DOP',
    (1, 5): 'NAV-ATT',
    (1, 6): 'NAV-SOL',
    (1, 7): 'NAV-PVT',
    (1, 9): 'NAV-ODO',
    (1, 16): 'NAV-RESETODO',
    (1, 17): 'NAV-VELECEF',
    (1, 18): 'NAV-VELNED',
    (1, 19): 'NAV-HPPOSECEF',
    (1, 20): 'NAV-HPPOSLLH',
    (1, 32): 'NAV-TIMEGPS',
    (1, 33): 'NAV-TIMEUTC',
    (1, 34): 'NAV-CLOCK',
    (1, 35): 'NAV-TIMEGLO',
    (1, 36): 'NAV-TIMEBDS',
    (1, 37): 'NAV-TIMEGAL',
    (1, 38): 'NAV-TIMELS',
    (1, 48): 'NAV-SVINFO',
    (1, 49): 'NAV-DGPS',
    (1, 50): 'NAV-SBAS',
    (1, 52): 'NAV-ORB',
    (1, 53): 'NAV-SAT',
    (1, 57): 'NAV-GEOFENCE',
    (1, 59): 'NAV-SVIN',
    (1, 60): 'NAV-RELPOSNED',
    (1, 66): 'NAV-SLAS',
    (1, 96): 'NAV-AOPSTATUS',
    (1, 97): 'NAV-EOE',
    (2, 19): 'RXM-SFRBX',
    (2, 20): 'RXM-MEASX',
    (2, 21): 'RXM-RAWX',
    (2, 32): 'RXM-SVSI',
    (2, 50): 'RXM-RTCM',
    (2, 65): 'RXM-PMREQ',
    (2, 89): 'RXM-RLM',
    (2, 97): 'RXM-IMES',
    (4, 1): 'INF-WARNING',
    (4, 2): 'INF-NOTICE',
    (4, 3): 'INF-TEST',
    (4, 4): 'INF-DEBUG',
    (5, 1): 'ACK-ACK',
    (6, 1): 'CFG-MSG',
    (6, 2): 'CFG-INF',
    (6, 4): 'CFG-RST',
    (6, 6): 'CFG-DAT',
    (6, 8): 'CFG-RATE',
    (6, 9): 'CFG-CFG',
    (6, 17): 'CFG-RXM',
    (6, 19): 'CFG-ANT',
    (6, 22): 'CFG-SBAS',
    (6, 23): 'CFG-NMEA',
    (6, 27): 'CFG-USB',
    (6, 30): 'CFG-ODO',
    (6, 35): 'CFG-NAVX5',
    (6, 36): 'CFG-NAV5',
    (6, 49): 'CFG-TP5',
    (6, 52): 'CFG-RINV',
    (6, 57): 'CFG-ITFM',
    (6, 59): 'CFG-PM2',
    (6, 61): 'CFG-TMODE2',
    (6, 62): 'CFG-GNSS',
    (6, 71): 'CFG-LOGFILTER',
    (6, 83): 'CFG-TXSLOT',
    (6, 87): 'CFG-PWR',
    (6, 92): 'CFG-HNR',
    (6, 96): 'CFG-ESRC',
    (6, 97): 'CFG-DOSC',
    (6, 98): 'CFG-SMGR',
    (6, 105): 'CFG-GEOFENCE',
    (6, 112): 'CFG-DGNSS',
    (6, 113): 'CFG-TMODE3',
    (6, 132): 'CFG-FIXSEED',
    (6, 133): 'CFG-DYNSEED',
    (6, 134): 'CFG-PMS',
    (6, 141): 'CFG-SLAS',
    (6, 147): 'CFG-BATCH',
    (9, 20): 'UPD-SOS',
    (10, 2): 'MON-IO',
    (10, 4): 'MON-VER',
    (10, 6): 'MON-MSGPP',
    (10, 7): 'MON-RXBUF',
    (10, 8): 'MON-TXBUF',
    (10, 9): 'MON-HW',
    (10, 11): 'MON-HW2',
    (10, 33): 'MON-RXR',
    (10, 39): 'MON-PATCH',
    (10, 40): 'MON-GNSS',
    (10, 46): 'MON-SMGR',
    (10, 50): 'MON-BATCH',
    (11, 1): 'AID-INI',
    (11, 2): 'AID-HUI',
    (11, 48): 'AID-ALM',
    (11, 49): 'AID-EPH',
    (11, 51): 'AID-AOP',
    (13, 1): 'TIM-TP',
    (13, 3): 'TIM-TM2',
    (13, 4): 'TIM-SVIN',
    (13, 6): 'TIM-VRFY',
    (13, 17): 'TIM-DOSC',
    (13, 18): 'TIM-TOS',
    (13, 19): 'TIM-SMEAS',
    (13, 21): 'TIM-VCOCAL',
    (13, 22): 'TIM-FCHG',
    (13, 23): 'TIM-HOC',
    (16, 2): 'ESF-MEAS',
    (16, 3): 'ESF-RAW',
    (16, 16): 'ESF-STATUS',
    (16, 21): 'ESF-INS',
    (19, 2): 'MGA-GAL',
    (19, 3): 'MGA-BDS',
    (19, 5): 'MGA-QZSS',
    (19, 6): 'MGA-GLO',
    (19, 32): 'MGA-ANO',
    (19, 33): 'MGA-FLASH',
    (19, 64): 'MGA-INI',
    (19, 96): 'MGA-ACK',
    (19, 128): 'MGA-DBD',
    (33, 3): 'LOG-ERASE',
    (33, 4): 'LOG-STRING',
    (33, 7): 'LOG-CREATE',
    (33, 8): 'LOG-INFO',
    (33, 9): 'LOG-RETRIEVE',
    (33, 14): 'LOG-FINDTIME',
    (33, 16): 'LOG-RETRIEVEBATCH',
    (33, 17): 'LOG-BATCH',
    (39, 1): 'SEC-SIGN',
    (39, 3): 'SEC-UNIQID',
    (40, 2): 'HNR-INS',
}
